version: '3'

services:
  app:
    build: .
    # 1 - É necessário executar pelo ao menos 1 vez no terminal: chmod +x .docker/entrypoint.sh
    # 2 - No momento que levantar o container do app e o container do DB, pode haver discrepancia do time entre eles.
    # Então, o dockerize tenta se comunicar durante 40s com o container do DB até levante primeiro o container DB 
    # para depois o container do app levantar e por assim se comunicar com os dados do container DB.
    entrypoint: dockerize -wait tcp://db:5432 -timeout 40s ./.docker/entrypoint.sh
    container_name: nestjs-api-app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    # Olhar o inicio do container db, mas não significa que o postgreSQL está totalmente levantado.
    # por isso a necessidade do entrypoint
    depends_on: 
      - db

  db:
    build: .docker/postgres
    container_name: nestjs-api-db
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=store
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data